spring:
  datasource:
    url: jdbc:mysql:///pingyin?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  second-datasource:
    url: jdbc:mysql:///Account_DB?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper 的映射文件路径
  type-aliases-package: com.heima.springbootmybatis.domain
#  config-location: # 指定 mybaits 的核型配置文件

